Repository trycourier/courier-node, pull requests merged in 2022-03, with the labels that each got.

#79 [C-5272] - node add list support to sdk and update docs
  CHANGELOG.md
  README.md
  src/__tests__/index.test.ts
  src/send/types.ts
Labels: ready for review

#81 Add support for message.tags
  CHANGELOG.md
  package.json
  src/client.ts
  src/send/types.ts
  src/types.ts
Labels: enhancement, ready for review

#90 [C-5575] Support message.brand_id
  CHANGELOG.md
  package.json
  src/send/types.ts
Labels: enhancement, ready for review

#88 [C-5556] adds support for audiences in courier
  CHANGELOG.md
  README.md
  package.json
  src/__tests__/audiences.test.ts
  src/audiences/index.ts
  src/audiences/types.ts
  src/client.ts
  src/send/types.ts
  src/types.ts
  tslint.json
Labels: enhancement, do-not-merge
